### ISSUE TITLE
Vagrant is unable to restart consul service 

### ISSUE THREAD

**Issue by isuftin** [johnbellone/consul-cookbook#107]
@johnbellone I'm not sure what the issue here is 
My Vagrantfile configuration: 

    config.vm.define "cs1", primary: true do |cs1|
    cs1.vm.hostname = "cs1.cida.vagrantup.com"
    cs1.vm.network "private_network", ip: "10.0.0.10"
    cs1.vm.provision :chef_zero do |chef|
      chef.data_bags_path = "data_bags"
      chef.json.merge!({
          :consul => {
            "servers" => ["10.0.0.10","10.0.0.11","10.0.0.12"],
            "service_mode" => "cluster"
          }
          })
        chef.run_list = ["consul::default"]    end
    end

==> cs1: [2015-01-12T19:02:02+00:00] INFO: service[consul] restarted
==> cs1: [2015-01-12T19:02:02+00:00] INFO: service[consul] enabled
==> cs1: [2015-01-12T19:02:02+00:00] INFO: directory[/usr/local/consul_ui-0.4.1] created directory /usr/local/consul_ui-0.4.1
==> cs1: [2015-01-12T19:02:04+00:00] INFO: remote_file[/var/chef/cache/consul_ui-0.4.1.zip] created file /var/chef/cache/consul_ui-0.4.1.zip
==> cs1: [2015-01-12T19:02:04+00:00] INFO: remote_file[/var/chef/cache/consul_ui-0.4.1.zip] updated file contents /var/chef/cache/consul_ui-0.4.1.zip
==> cs1: [2015-01-12T19:02:04+00:00] INFO: remote_file[/var/chef/cache/consul_ui-0.4.1.zip] not queuing delayed action run on execute[unpack /var/chef/cache/consul_ui-0.4.1.zip] (delayed), as it's already been queued
==> cs1: [2015-01-12T19:02:04+00:00] INFO: link[/var/lib/consul/ui] created
==> cs1: [2015-01-12T19:02:04+00:00] INFO: directory[/usr/local/consul_ui-0.4.1] sending run action to execute[unpack /var/chef/cache/consul_ui-0.4.1.zip] (delayed)
==> cs1: [2015-01-12T19:02:04+00:00] INFO: execute[unpack /var/chef/cache/consul_ui-0.4.1.zip] ran successfully
==> cs1: [2015-01-12T19:02:04+00:00] INFO: execute[unpack /var/chef/cache/consul_ui-0.4.1.zip] sending run action to execute[set owner on /usr/local/consul_ui-0.4.1] (delayed)
==> cs1: [2015-01-12T19:02:04+00:00] INFO: execute[set owner on /usr/local/consul_ui-0.4.1] ran successfully
==> cs1: [2015-01-12T19:02:04+00:00] INFO: file[/etc/consul.d/default.json] sending restart action to service[consul] (delayed)
==> cs1:
==> cs1: ================================================================================
==> cs1: Error executing action `restart` on resource 'service[consul]'
==> cs1: ================================================================================
==> cs1:
==> cs1:
==> cs1: Mixlib::ShellOut::ShellCommandFailed
==> cs1: ------------------------------------
==> cs1: Expected process to exit with [0], but received '1'
==> cs1:
==> cs1: ---- Begin output of /sbin/service consul restart ----
==> cs1:
==> cs1: STDOUT: Stopping consul.............
==> cs1:
==> cs1: consul not stopped; may still be shutting down or shutdown may have failed
==> cs1:
==> cs1: Unable to stop consul, will not attempt to start
==> cs1:
==> cs1: STDERR:
==> cs1:
==> cs1: ---- End output of /sbin/service consul restart ----
==> cs1:
==> cs1: Ran /sbin/service consul restart returned 1
==> cs1:
==> cs1:
==> cs1: Resource Declaration:
==> cs1: ---------------------
==> cs1: # In /tmp/vagrant-chef/83bff0467b4d77d5a69d8ce31da32616/cookbooks/consul/recipes/_service.rb
==> cs1:
==> cs1: 211:   service 'consul' do
==> cs1: 212:     provider Chef::Provider::Service::Upstart if platform?("ubuntu")
==> cs1: 213:     supports status: true, restart: true, reload: true
==> cs1: 214:     action [:enable, :start]
==> cs1: 215:     subscribes :restart, "file[#{consul_config_filename}", :delayed
==> cs1: 216:   end
==> cs1: 217: when 'runit'
==> cs1:
==> cs1: Compiled Resource:
==> cs1: ------------------
==> cs1: # Declared in /tmp/vagrant-chef/83bff0467b4d77d5a69d8ce31da32616/cookbooks/consul/recipes/_service.rb:211:in `from_file'
==> cs1:
==> cs1: service("consul") do
==> cs1:   action [:enable, :start]
==> cs1:   updated true
==> cs1:   supports {:status=>true, :restart=>true, :reload=>true}
==> cs1:   retries 0
==> cs1:   retry_delay 2
==> cs1:   default_guard_interpreter :default
==> cs1:   service_name "consul"
==> cs1:   enabled true
==> cs1:   running true
==> cs1:   pattern "consul"
==> cs1:   declared_type :service
==> cs1:   cookbook_name :consul
==> cs1:   recipe_name "_service"
==> cs1: end
==> cs1:
==> cs1: [2015-01-12T19:02:15+00:00] ERROR: Running exception handlers
==> cs1: [2015-01-12T19:02:15+00:00] ERROR: Exception handlers complete
==> cs1: [2015-01-12T19:02:15+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> cs1: [2015-01-12T19:02:15+00:00] ERROR: service[consul] (consul::_service line 211) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> cs1: ---- Begin output of /sbin/service consul restart ----
==> cs1: STDOUT: Stopping consul.............
==> cs1: consul not stopped; may still be shutting down or shutdown may have failed
==> cs1: Unable to stop consul, will not attempt to start
==> cs1: STDERR:
==> cs1: ---- End output of /sbin/service consul restart ----
==> cs1: Ran /sbin/service consul restart returned 1
==> cs1: [2015-01-12T19:02:16+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

The ouput: 

# cat /var/chef/cache/chef-stacktrace.out
Generated at 2015-01-12 19:02:15 +0000
Mixlib::ShellOut::ShellCommandFailed: service[consul] (consul::_service line 211) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/service consul restart ----
STDOUT: Stopping consul.............
consul not stopped; may still be shutting down or shutdown may have failed
Unable to stop consul, will not attempt to start
STDERR:
---- End output of /sbin/service consul restart ----
Ran /sbin/service consul restart returned 1
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:267:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:254:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:60:in `shell_out_with_systems_locale!'
/opt/chef/embedded/apps/chef/lib/chef/provider/service/init.rb:75:in `restart_service'
/opt/chef/embedded/apps/chef/lib/chef/provider/service.rb:115:in `block in action_restart'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/service.rb:114:in `action_restart'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:111:in `run_delayed_notification'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:99:in `block in run_delayed_notifications'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:98:in `run_delayed_notifications'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:88:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:315:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:400:in `block in run'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:40:in `load'
/usr/bin/chef-solo:40:in `<main>'

**Comment by isuftin** [comment]
Note: This is being done in CentOS-65

**Comment by isuftin** [comment]
An update. I've figured out a decent Vagrantfile that works. The issue described above is when you feed an array of servers to a cluster that may not yet exist. (e.g. ["10.0.0.10","10.0.0.11","10.0.0.12"] ). If those servers don't exist, the consul service will not restart properly. I would consider this a bug but I don't know whether it's a bug in the cookbook or in the consul application itself. 

Anyway, my Vagrantfile that works well to bring up 3 cluster nodes and a client node. The clusters are limited to 256M of RAM as I don't need them any larger. The CentOS image is one we Packer'd for our org but is essentially the base CentOS 6.6.  The client is given the full server list since by the time the client comes up (unless Vagrant Up is done via --parallel) the cluster nodes are up and ready for connections. I bind the consul services to eth1 as those offer the 10.0.0.x address instead of eth0 which offers the DHCP address :

    Vagrant.configure(2) do |config|
      config.omnibus.chef_version = :latest
      config.berkshelf.enabled = true
  
      (1..3).each do |i|
        config.vm.define "cluster-#{i}", primary: true do |node|
          node.vm.network "private_network", ip: "10.0.0.1#{i}"
          node.vm.provider "vmware_fusion" do |v|
            v.vmx["memsize"] = "256"
          end
          node.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--memory", "256"]
          end
          node.vm.provision :chef_solo do |chef|
            chef.add_recipe "consul::default"
            chef.json.merge!({
                :consul => {
                  "servers" => ["10.0.0.11"],
                  "service_mode" => "cluster",
                  "bootstrap_expect" => "3",
                  "retry_on_join" => true,
                  "enable_syslog" => true,
                  "log_level" => "debug",
                  "node_name" => "cluster-#{i}",
                  "advertise_addr" => "10.0.0.1#{i}",
                  "bind_interface" => "eth1",
                  "advertise_interface" => "eth1"
                }
              })
            end
        end
      end

      config.vm.define "agent" do |node|
        node.vm.network "private_network", ip: "10.0.0.20"
        node.vm.provision :chef_solo do |chef|
          chef.add_recipe "consul::default"
          chef.json.merge!({
              :consul => {
                "servers" => ["10.0.0.11","10.0.0.12","10.0.0.13"],
                "service_mode" => "client",
                "retry_on_join" => true,
                "enable_syslog" => true,
                "log_level" => "debug",
                "node_name" => "consul-agent",
                "advertise_addr" => "10.0.0.20",
                "bind_interface" => "eth1",
                "advertise_interface" => "eth1"
              }
            })
        end
      end
    end
