### ISSUE TITLE
Missing package on RHEL7 AWS

### ISSUE THREAD

**Issue by marc-** [johnbellone/consul-cookbook#165]
cloud Amazon EC2
Red Hat Enterprise Linux Server release 7.1 (Maipo)
consul-cookbook version 0.9.1
```
==> consul:   package[libarchive-devel] (libarchive::default line 25) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for libarchive-devel
==> consul:   
==> consul:   Cookbook Trace:
==> consul:   ---------------
==> consul:     /tmp/vagrant-chef-2/chef-solo-1/cookbooks/libarchive/recipes/default.rb:27:in `from_file'
==> consul:     /tmp/vagrant-chef-2/chef-solo-1/cookbooks/consul/recipes/install_binary.rb:18:in `from_file'
==> consul:     /tmp/vagrant-chef-2/chef-solo-1/cookbooks/consul/recipes/default.rb:20:in `from_file'
==> consul:     /tmp/vagrant-chef-2/chef-solo-1/cookbooks/rf-haproxy-consul/recipes/server.rb:11:in `from_file'
==> consul:   
==> consul:   Relevant File Content:
==> consul:   ----------------------
==> consul:   /tmp/vagrant-chef-2/chef-solo-1/cookbooks/libarchive/recipes/default.rb:
==> consul:   
==> consul:    20:    end.run_action(:install)
==> consul:    21:  when platform_family?("rhel")
==> consul:    22:    package "libarchive" do
==> consul:    23:      action :nothing
==> consul:    24:    end.run_action(:install)
==> consul:    25:    package "libarchive-devel" do
==> consul:    26:      action :nothing
==> consul:    27>>   end.run_action(:install)
==> consul:    28:  when platform_family?("arch")
==> consul:    29:    package "libarchive" do
==> consul:    30:      action :nothing
==> consul:    31:    end.run_action(:install)
==> consul:    32:  when platform_family?("mac_os_x")
==> consul:    33:    package "libarchive" do
==> consul:    34:      action :nothing
==> consul:    35:    end.run_action(:install)
==> consul:    36:  else
==> consul:   
==> consul:   
==> consul:   Running handlers:
==> consul: [2015-04-21T11:40:45-04:00] ERROR: Running exception handlers
==> consul:   Running handlers complete
==> consul: [2015-04-21T11:40:45-04:00] ERROR: Exception handlers complete
==> consul: [2015-04-21T11:40:45-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> consul:   Chef Client failed. 0 resources updated in 29.007043215 seconds
==> consul: [2015-04-21T11:40:46-04:00] ERROR: package[libarchive-devel] (libarchive::default line 25) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for libarchive-devel
==> consul: [2015-04-21T11:40:46-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
AWS yum repo doesn't contain package libarchive-devel:
```
$ yum search libarchive
Loaded plugins: amazon-id, rhui-lb
=============================================== N/S matched: libarchive ================================================
libarchive.i686 : A library for handling streaming archive formats
libarchive.x86_64 : A library for handling streaming archive formats
```
I suggest to use cookbook [ark](https://github.com/burtlo/ark) instead of libarchive .

**Comment by johnbellone** [comment]
#169
