### ISSUE TITLE
regression of allowing http checks

### ISSUE THREAD

**Issue by sge-babrams** [johnbellone/consul-cookbook#206]
I am getting this while trying to converge on 1.0.0:

```
  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/aio-elasticsearch/recipes/logs.rb
  ================================================================================
  
  Chef::Exceptions::ValidationFailed
  ----------------------------------
  Option check's value {:interval=>"10s", :http=>"http://localhost:9200", :timeout=>"2s"} Checks must be a hash containing either a `:ttl` key/value or a `:script` and `:interval` key/value!
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/aio-elasticsearch/recipes/logs.rb:9:in `block in from_file'
    /var/chef/cache/cookbooks/aio-elasticsearch/recipes/logs.rb:3:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/aio-elasticsearch/recipes/logs.rb:
  
    2:  
    3:  consul_service_def 'elasticsearch-logs' do
    4:    port 9200
    5:    # tags ['sometag']
    6:    check(
    7:      interval: '10s',
    8:      http: 'http://localhost:9200',
    9>>     timeout: '2s'
   10:  
   11:    #   script: 'echo ok'
   12:    )
   13:    notifies :reload, 'service[consul]'
   14:  end
   15:  
 ```

The functionality was added here:  https://github.com/johnbellone/consul-cookbook/pull/143

**Comment by sge-babrams** [comment]
Working as of 0.11.1

**Comment by johnbellone** [comment]
The HWRP has changed.

**Comment by johnbellone** [comment]
Please take a look at the README to understand what has changed.
